# Target specific macros
TARGET = n3dscan
TARGET_SOURCES := \
	main.c
#	DistNx_API.c
TOPPERS_OSEK_OIL_SOURCE = ./n3dscan.oil
USER_DEF = NO_RUN_ENTER_STOP_EXIT

WAV_SOURCES := \
	boot_snd.wav

BMP_SOURCES := \
#	proc_circle.bmp \
#	proc_circle_highlight.bmp \
#	icon_done.bmp \
#	icon_failed.bmp \
#	icon_bt_wait.bmp \
#	icon_bt_conn.bmp

BUILD_MODE = ROM_ONLY

# Don't modify below part
O_PATH ?= build

# Modify me
include ../nxtOSEK/ecrobot/ecrobot.mak
